### ISSUE TITLE
"dump" functionality isn't really a thing

### ISSUE THREAD

**Issue by katmit** [katmit/ASE_Proj1#13]
i'm not even sure what the feature does in the original code. this needs to be investigated

**Comment by katmit** [comment]
this might be as simple as adding a try-catch in the main method and only printing the stack if the dump flag is set

**Comment by het-patel99** [comment]
yes, it seems like that!! Also, that is not used in provided tests.

**Comment by katmit** [comment]
whoever "grabs" this card, fill in that todo test for this scenario please
